name: matfusion
dependencies:
  - python=3.10
  - pip
  - pip:
    - --find-links https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
    - jax[cuda11]
    - optax==0.1.4
    - memory_efficient_attention==0.1.3
    - flax==0.6.8
    - tensorflow==2.8.4
    - torch==2.0.1
    - numpy==1.24.2
    - urllib3==1.26.15
    - wandb==0.14.1
    - imageio==2.19.5
    - ffmpegio==0.8.3
    - ffmpegio==0.8.3
    - diffusers==0.20.0
    - lpips_jax==0.1.0
    - ipython==8.17.2
    - opencv-python==4.8.1.78
    - ffmpegio
